baseURL = 'http://blog.fernandoes.dev.br'
languageCode = 'en-us'
title = 'Luiz Fernando F.'
theme = 'cactus'

[params]
	description = "Estudante de computação e entusiasta de segurança da informação e novas tecnologias. Desde pequeno tive fascínio por computadores e procurava entender melhor como eles funcionavam, gosto de objetivos ambiciosos e de pensar em como podemos antecipar o futuro. Trabalhar com software é muito interessante e quero participar de projetos desse tipo."
	mainSection = "posts"
	mainSectionTitle = "Posts"
	showProjectsList = false
	projectsUrl = "https://github.com/fernxndk"	
	css = ["css/custom.css"]
	colortheme = "classic"
	
[[params.social]]
  name = "github"
  link = "https://github.com/fernxndk"

[[params.social]]
  name = "email"
  link = "work.luizfernando.dev@outlook.com"

# Main menu which appears below site header.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3
